#:kivy 1.0.0


ScreenManagement:
    Screen1:
    Screen2:
    Screen3:
    Screen4:
    Screen5:
	
<Screen1>:
    name: 'home'

    Button:
        on_release: app.root.current = 'personal_info'
        text: 'New User'
        size_hint:.5,1
        background_color: (1,0,0,1)
        font_size: 50

    Button:
        on_release: app.root.current = 'control'
        text: 'Existing User'
        size_hint: .5,1
        pos: 958,1
        background_color: (1,1,0,1)
        font_size: 50
            
<Screen2>:
    name: 'personal_info'

    Button:
        text: 'Go to Control'

    Button:
        on_release: app.root.current = 'control'
        text: 'Go to Control'
        font_size: 25
        size_hint: .2,.1

<Screen3>:
    name: 'emergency_contact'
    
    Button:
        on_release: app.root.current = 'control'
        text: 'Emergency contact screen >> Go to Control'
        font_size: 50

    Button:
        on_release: app.root.current = 'control'
        text: 'Go to Control'
        font_size: 25
        size_hint: .2,.1    

<Screen4>:
    name: 'control'

    Button:
        text: 'Control screen'
        font_size: 50

    Button:
        on_release: app.root.current = 'home'
        text: 'Go back home'
        font_size: 25
        size_hint: .2,.1